export const SOCIAL_LINKS = [
  {
    icon: "Github",
    name: "GitHub",
    route: "https://github.com/lakshyamahawar14",
  },
  {
    icon: "Linkedin",
    name: "LinkedIn",
    route: "https://www.linkedin.com/in/lakshya-mahawar-099788209/",
  },
  {
    icon: "Instagram",
    name: "Instagram",
    route: "https://www.instagram.com/freaky.lakshya/",
  },
  {
    icon: "Code2",
    name: "LeetCode",
    route: "https://leetcode.com/lakshyamahawar14/",
  },
  {
    icon: "Keyboard",
    name: "10FastFingers",
    route: "https://10fastfingers.com/user/2769484/",
  },
];

export const INTERESTS = [
  "Competitive Programming",
  "Web Development",
  "Web Scraping",
  "Data Structures & Algorithms",
  "Machine Learning",
];

export const EDUCATION = [
  {
    year: 2024,
    examination: "B.Tech (ECE)",
    institution: "Indian Institute of Technology, Roorkee",
    score: "7.348",
  },
  {
    year: 2020,
    examination: "Intermediate (Class XII)",
    institution: "D S Science Academy, Gangapur City (RBSE)",
    score: "96.4%",
  },
  {
    year: 2018,
    examination: "Matriculate (Class X)",
    institution: "Jyoti Shikshan Sansthan, Piplai (RBSE)",
    score: "96.17%",
  },
];

export const SKILLS = [
  {
    name: "Computer Languages",
    values: [
      { name: "C++", proficiency: "Advanced" },
      { name: "Python", proficiency: "Intermediate" },
      { name: "Java", proficiency: "Beginner" },
      { name: "JavaScript", proficiency: "Intermediate" },
      { name: "TypeScript", proficiency: "Intermediate" },
    ],
  },
  {
    name: "Software Packages",
    values: [
      { name: "Git", proficiency: "Intermediate" },
      { name: "GitHub", proficiency: "Intermediate" },
      { name: "VS Code", proficiency: "Advanced" },
      { name: "MATLAB", proficiency: "Beginner" },
      { name: "LTspice", proficiency: "Beginner" },
    ],
  },
  {
    name: "Additional Courses",
    values: [
      {
        name: "Fundamentals of Object-Oriented Programming",
        proficiency: "Advanced",
      },
      { name: "Data Structures", proficiency: "Advanced" },
      {
        name: "Data Mining for Business Intelligence",
        proficiency: "Intermediate",
      },
      {
        name: "Machine Learning in Semiconductor Industry",
        proficiency: "Intermediate",
      },
      { name: "Probability and Statistics", proficiency: "Advanced" },
    ],
  },
  {
    name: "Languages Known",
    values: [
      { name: "Hindi", proficiency: "Advanced" },
      { name: "English", proficiency: "Advanced" },
    ],
  },
];

export const INTERNSHIPS = [
  {
    start: "May 2023",
    end: "June 2023",
    period: 1,
    role: "Web Developer",
    organization: "IIT Roorkee",
    score: "7.348",
    details: {
      title: "Cognitive Therapy Chatbot Using Prompt Learning",
      description: [
        "Split the project into frontend and backend and improved the web interface of the chatbot application.",
        "Utilizing GPT-3.5 API and prompt learning, improved the responses generated by the chatbot.",
        "Added mental health blogs, custom assessment tests and community forums to the website.",
      ],
    },
    tools: [
      "ReactJS",
      "Firebase",
      "NodeJS",
      "GPT-3.5",
      "ChatGPT",
      "SCSS",
      "Recoil",
    ],
  },
];

export const PROJECTS = [
  {
    start: "January 2023",
    end: "April 2023",
    period: 4,
    organization: "IIT Roorkee",
    details: {
      title: "Dynamic Maze Generation Game",
      description: [
        "Developed a Python-based maze game capable of generating mazes of desired size and difficulty (level), analyzing their difficulty and solving them.",
        "Kruskal's algorithm was used to generate the maze data.",
        "Machine learning models like Logistic regression and SVM were used to predict the difficulty of the generated mazes.",
        "PyGame library was used to create the graphical interface for the game.",
      ],
    },
    tools: [
      "Python",
      "Scikit-learn",
      "Numpy",
      "Pandas",
      "Pygame",
      "Graphs",
      "Backtracking",
    ],
    link: "https://maze-ai.netlify.app/",
    imageSrc: "/images/maze_ai.png",
  },
  {
    start: "July 2022",
    end: "July 2022",
    period: 1,
    organization: "Self Project",
    details: {
      title: "Visual React Tool",
      description: [
        "Created a web application to generate code for ReactJS applications by joining blueprints (set of predefined components) visually.",
        "Frontend was created using Svelte framework and OpenAI API was used in the backend.",
      ],
    },
    tools: ["SvelteKit", "NodeJS", "GPT-3.5", "ChatGPT"],
    link: "https://visual-react.vercel.app/",
    imageSrc: "/images/visual_react.png",
  },
  {
    start: "Dec 2021",
    end: "Dec 2021",
    period: 1,
    organization: "Self Project",
    details: {
      title: "Questa Web",
      description: [
        "It's a question paper making website where its users can put questions and get a PDF generated.",
        "This is made using NextJS and HTML2PDF API is used for PDF generation.",
      ],
    },
    tools: ["NextJS", "HTML2PDF"],
    link: "https://questaweb.vercel.app/",
    imageSrc: "/images/questa_web.png",
  },
  {
    start: "October 2022",
    end: "November 2022",
    period: 1,
    organization: "IIT Roorkee",
    details: {
      title: "Clustering Queries For Enhanced Customer Support",
      description: [
        "Utilized NLTK library in Python for processing of customer queries dataset.",
        "KMeans and GMM algorithms were used to cluster queries of similar types.",
      ],
    },
    tools: ["Python", "NLTK", "NLP", "Clustering", "Sentiment Analysis"],
  },
  {
    start: "June 2021",
    end: "July 2021",
    period: 2,
    organization: "IIT Roorkee",
    details: {
      title: "A Hardware Architecture Design For Realtime Gaussian Filter",
      description: [
        "Wrote a Python program to convert the JPG and PNG image formats to bitmap file format.",
        "Wrote a MATLAB program to convert data of bitmap file format to Hexadecimal data for the ease of computation.",
      ],
    },
    tools: ["MATLAB", "Python", "Image Processing"],
  },
];

export const PORS = [
  {
    start: "Jan 2021",
    end: "July 2021",
    period: 6,
    role: "Volunteer",
    organization: "National Service Scheme, IIT Roorkee",
    details: {
      title: "",
      description: [
        "Contacting with participants of National Social Summit, an Annual Fest of NSS, IIT Roorkee",
      ],
    },
  },
  {
    start: "Aug 2021",
    end: "Jan 2022",
    period: 6,
    role: "Web Developer",
    organization: "National Service Scheme, IIT Roorkee",
    details: {
      title: "",
      description: [
        "Debugging and Maintaining National Social Summit website.",
      ],
    },
    tools: ["Django", "Burpe Suite"],
  },
];