import React from "react";
import Heading from "./heading";
import Card from "./card";

const internships = [
  {
    start: "May 2023",
    end: "June 2023",
    period: 1,
    role: "Web Developer",
    organization: "IIT Roorkee",
    score: "7.348",
    details: {
      title: "Cognitive Therapy Chatbot Using Prompt Learning",
      description: [
        "Split the project into frontend and backend and improved the web interface of the chatbot application.",
        "Utilizing GPT-3.5 API and prompt learning, improved the responses generated by the chatbot.",
        "Added mental health blogs, custom assessment tests and community forums to the website.",
      ],
    },
    tools: [
      "ReactJS",
      "Firebase",
      "NodeJS",
      "GPT-3.5",
      "ChatGPT",
      "SCSS",
      "Recoil",
    ],
  },
];

const Internships = () => {
  return (
    <div className="flex flex-col w-full">
      <Heading headingText={"Internship"} headingSize="small" />
      {internships.map((intern, index) => (
        <Card
          key={index}
          start={intern.start}
          end={intern.end}
          period={intern.period}
          role={intern.role}
          organization={intern.organization}
          details={intern.details}
          tools={intern.tools}
        />
      ))}
    </div>
  );
};

export default Internships;
